@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jan 29 16:30:11 +0000 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim key_schedule_tb_behav -key {Behavioral:sim_1:Functional:key_schedule_tb} -tclbatch key_schedule_tb.tcl -view C:/Users/96doh/PRESENT/PRESENT-80/PRESENT/key_schedule_tb_behav.wcfg -log simulate.log"
call xsim  key_schedule_tb_behav -key {Behavioral:sim_1:Functional:key_schedule_tb} -tclbatch key_schedule_tb.tcl -view C:/Users/96doh/PRESENT/PRESENT-80/PRESENT/key_schedule_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
